spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/todolist
    username: postgres
    password: 123
    driverClassName: org.postgresql.Driver
  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQL82Dialect

bot:
  name: ToDoListBot
  token: 5610627690:AAHBq3KzQr2WUKU5oOMCDu9nfHQzhPJAoTA










